name: build-images
on:
  push:
    branches:
      - "*"

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 登录阿里云
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALI_USER  }}
          password: ${{ secrets.ALI_PASSWORD  }}
      - name: 构建 base 镜像
        uses: docker/build-push-action@v2
        with:
          context: ./base
          file: ./base/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            mereith/coder-base
            registry.cn-beijing.aliyuncs.com/mereith/coder-base
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 登录阿里云
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALI_USER  }}
          password: ${{ secrets.ALI_PASSWORD  }}
      - name: 构建 node 镜像
        uses: docker/build-push-action@v2
        with:
          context: ./node
          file: ./node/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            mereith/coder-node
            registry.cn-beijing.aliyuncs.com/mereith/coder-node
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 登录阿里云
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALI_USER  }}
          password: ${{ secrets.ALI_PASSWORD  }}
      - name: 构建 go 镜像
        uses: docker/build-push-action@v2
        with:
          context: ./go
          file: ./go/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            mereith/coder-go
            registry.cn-beijing.aliyuncs.com/mereith/coder-go
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 登录阿里云
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALI_USER  }}
          password: ${{ secrets.ALI_PASSWORD  }}
      - name: 构建 python 镜像
        uses: docker/build-push-action@v2
        with:
          context: ./python
          file: ./python/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            mereith/coder-python
            registry.cn-beijing.aliyuncs.com/mereith/coder-python
  jupyter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 登录阿里云
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALI_USER  }}
          password: ${{ secrets.ALI_PASSWORD  }}
      - name: 构建 jupyter 镜像
        uses: docker/build-push-action@v2
        with:
          context: ./jupyter
          file: ./jupyter/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            mereith/coder-jupyter
            registry.cn-beijing.aliyuncs.com/mereith/coder-jupyter
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 登录阿里云
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALI_USER  }}
          password: ${{ secrets.ALI_PASSWORD  }}
      - name: 构建 rust 镜像
        uses: docker/build-push-action@v2
        with:
          context: ./rust
          file: ./rust/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            mereith/coder-rust
            registry.cn-beijing.aliyuncs.com/mereith/coder-rust
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 登录阿里云
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALI_USER  }}
          password: ${{ secrets.ALI_PASSWORD  }}
      - name: 构建 java 镜像
        uses: docker/build-push-action@v2
        with:
          context: ./java
          file: ./java/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            mereith/coder-java
            registry.cn-beijing.aliyuncs.com/mereith/coder-java
  vnc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 登录阿里云
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALI_USER  }}
          password: ${{ secrets.ALI_PASSWORD  }}
      - name: 构建 vnc 镜像
        uses: docker/build-push-action@v2
        with:
          context: ./vnc
          file: ./vnc/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            mereith/coder-vnc
            registry.cn-beijing.aliyuncs.com/mereith/coder-vnc



